INSERT INTO review (booking_id, comment, hotel_score, room_score) VALUES
    (1, 'Great hotel, excellent service!', 5, 4),
    (2, 'Nice stay, friendly staff.', 4, 3),
    (3, 'Clean room, comfortable bed.', 5, 5),
    (4, 'Disappointed with cleanliness.', 3, 2),
    (5, 'Beautiful view from the room.', 5, 4),
    (6, 'Average experience, could be better.', 3, 3),
    (7, 'Fantastic hotel, highly recommend!', 5, 5),
    (8, 'Good value for money.', 4, 4),
    (9, 'Issues with noise at night.', 3, 2),
    (10, 'Lovely atmosphere, attentive staff.', 5, 5),
    (11, 'Room was small but clean.', 4, 3),
    (12, 'Great location, close to attractions.', 5, 4),
    (13, 'Had a pleasant stay overall.', 4, 4),
    (14, 'Comfortable room, good amenities.', 5, 5),
    (15, 'Room service was slow.', 3, 2);