INSERT INTO hotel (hotel_name, country, city, address, rating) VALUES 
    ('Sunset Hotel', 'Italy', 'Rome', 'Via del Corso, 123', 4.2),
    ('Ocean View Resort', 'Spain', 'Barcelona', 'Carrer de Balmes, 56', 4.5),
    ('Mountain Lodge', 'Switzerland', 'Zurich', 'Bahnhofstrasse, 7', 4.8),
    ('City Lights Inn', 'France', 'Paris', 'Rue de Rivoli, 89', 4.0),
    ('Seaside Retreat', 'Greece', 'Athens', 'Syntagma Square, 15', 4.3),
    ('Forest Haven Hotel', 'Germany', 'Berlin', 'Unter den Linden, 33', 4.6),
    ('Lakeside Resort', 'Switzerland', 'Geneva', 'Quai du Mont-Blanc, 21', 4.9),
    ('Downtown Plaza Hotel', 'Spain', 'Madrid', 'Gran Via, 98', 4.1),
    ('Mountain View Lodge', 'Austria', 'Vienna', 'Stephansplatz, 5', 4.7),
    ('Beachfront Oasis', 'Italy', 'Venice', 'Piazza San Marco, 10', 4.4),
    ('Urban Retreat Hotel', 'France', 'Nice', 'Promenade des Anglais, 30', 4.2),
    ('Riverside Inn', 'Germany', 'Munich', 'Marienplatz, 12', 4.5),
    ('Hilltop Hideaway Hotel', 'Austria', 'Salzburg', 'Getreidegasse, 20', 4.6),
    ('Coastal Escape Resort', 'Greece', 'Santorini', 'Fira Square, 8', 4.3),
    ('Skyline View Hotel', 'Spain', 'Valencia', 'Plaza del Ayuntamiento, 15', 4.8);